# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20170424_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='short_description',
            new_name='description',
        ),
    ]
