# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20170429_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='instructions',
            new_name='methods',
        ),
    ]
