# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 20:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20170430_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(default='', max_length=1000, validators=[django.core.validators.URLValidator]),
            preserve_default=False,
        ),
    ]
